xconnector:
  enabled: true
  mode: embedded
  offline_mode: true

  etcd:
    endpoints: ['http://127.0.0.1:2379']
    timeout: 5
    enabled: true

  nats:
    url: 'nats://127.0.0.1:4222'
    timeout: 5
    enabled: true

  cache:
    provider: memory
    max_size: 1GB
    ttl: 3600

  kv_transfer:
    connector: DynamoNixlConnector
    batch_size: 1000
    compression: false

  logging:
    level: INFO
    file: /workspace/logs/xconnector.log
    console: true

  fault_tolerance:
    graceful_degradation: true
    retry_attempts: 3
    offline_fallback: true

sdk:
  mode: embedded
  enable_kv_cache: true
  enable_distributed: true

  adapters:
    - name: lmcache
      type: cache
      class_path: xconnector.adapters.cache.lmcache_adapter.LMCacheAdapter
      config:
        storage_backend: memory
        max_cache_size: 1024
        enable_compression: true
        block_size: 16
      enabled: true
      priority: 1