version: '3.8'

services:
  # XConnector 独立服务
  xconnector-service:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile.xconnector-service
    container_name: xconnector-service
    environment:
      - ETCD_HOST=etcd
      - ETCD_PORT=2379
      - NATS_URL=nats://nats:4222
      - XCONNECTOR_PORT=8081
      - LOG_LEVEL=INFO
      - PYTHONPATH=/app
    networks:
      - dynamo-network
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      etcd:
        condition: service_healthy
      nats:
        condition: service_started
    volumes:
      - xconnector-logs:/app/logs

  # AI-Dynamo Worker (使用你提供的Dynamo镜像)
  dynamo-worker:
    image: ${DYNAMO_IMAGE:-ai-dynamo:latest}
    container_name: dynamo-worker
    environment:
      # XConnector 配置
      - ENABLE_XCONNECTOR=true
      - XCONNECTOR_SERVICE_URL=http://xconnector-service:8081
      # Dynamo 配置
      - ETCD_HOST=etcd
      - ETCD_PORT=2379
      - NATS_URL=nats://nats:4222
      # Python 路径配置
      - PYTHONPATH=/workspace:/xconnector-integration:$PYTHONPATH
    volumes:
      # 挂载配置文件到Dynamo工作目录
      - ./configs/disagg_xconnector_remote.yaml:/workspace/configs/disagg.yaml:ro
      # 挂载XConnector集成代码
      - ../../integrations/dynamo/extension_loader.py:/xconnector-integration/extension_loader.py:ro
      # 挂载启动包装脚本
      - ./dynamo-wrapper/startup-wrapper.py:/workspace/startup-wrapper.py:ro
      # 挂载模型缓存目录
      - model-cache:/workspace/models
      # 挂载日志目录
      - dynamo-logs:/workspace/logs
    networks:
      - dynamo-network
    # 使用包装脚本启动
    command: ["python", "/workspace/startup-wrapper.py", "serve", "graphs.disagg:Frontend", "-f", "/workspace/configs/disagg.yaml"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      xconnector-service:
        condition: service_healthy
      etcd:
        condition: service_healthy
      nats:
        condition: service_started

  # Frontend service (如果需要独立的前端)
  dynamo-frontend:
    image: ${DYNAMO_IMAGE:-ai-dynamo:latest}
    container_name: dynamo-frontend
    environment:
      - ETCD_HOST=etcd
      - ETCD_PORT=2379
      - PYTHONPATH=/workspace:$PYTHONPATH
    volumes:
      - ./configs/disagg_xconnector_remote.yaml:/workspace/configs/disagg.yaml:ro
    networks:
      - dynamo-network
    ports:
      - "8000:8000"
    command: ["dynamo", "serve", "graphs.disagg:Frontend", "-f", "/workspace/configs/disagg.yaml"]
    depends_on:
      dynamo-worker:
        condition: service_started

  # etcd
  etcd:
    image: quay.io/coreos/etcd:v3.5.9
    container_name: etcd
    environment:
      - ETCD_NAME=etcd0
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER=etcd0=http://etcd:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
    networks:
      - dynamo-network
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd-data:/etcd-data
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # NATS
  nats:
    image: nats:2.10-alpine
    container_name: nats
    networks:
      - dynamo-network
    ports:
      - "4222:4222"
      - "8222:8222"  # HTTP monitoring
    command: ["-js", "-m", "8222"]  # Enable JetStream
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  dynamo-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  etcd-data:
  xconnector-logs:
  dynamo-logs:
  model-cache: