version: '3.8'

services:
  # XConnector 服务 - 使用已有镜像
  xconnector-service:
    image: xconnector-service:latest
    container_name: xconnector-service
    environment:
      - XCONNECTOR_PORT=8081
      - LOG_LEVEL=INFO
      - PYTHONPATH=/app
    networks:
      - xconnector-net
    ports:
      - "8081:8081"
    volumes:
      - xconnector-logs:/app/logs
    restart: unless-stopped

  # etcd - 使用你的 bitnami 镜像，修改端口避免冲突
  etcd:
    image: bitnami/etcd:auth-online
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2381  # 改为 2381
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2381
      - ETCD_INITIAL_CLUSTER=etcd=http://etcd:2381
      - ETCD_NAME=etcd
    networks:
      - xconnector-net
    ports:
      - "2379:2379"
      - "2381:2381"  # 改为 2381
    volumes:
      - etcd-data:/bitnami/etcd/data
    restart: unless-stopped

  # NATS - 使用你的 latest 镜像
  nats:
    image: nats:latest
    container_name: nats
    networks:
      - xconnector-net
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js", "-m", "8222"]
    restart: unless-stopped

  # Dynamo Worker - 使用你的镜像
  dynamo-worker:
    image: dynamo:latest-vllm
    container_name: dynamo-worker
    environment:
      - ENABLE_XCONNECTOR=false  # 暂时禁用，避免复杂的集成问题
      - PYTHONPATH=/workspace
      # 如果需要 GPU，取消下面的注释
      # - NVIDIA_VISIBLE_DEVICES=all
    networks:
      - xconnector-net
    ports:
      - "8000:8000"  # Dynamo API 端口
    volumes:
      - dynamo-logs:/workspace/logs
      - model-cache:/workspace/models
    # GPU 支持（如果需要）
    deploy:
       resources:
         reservations:
           devices:
             - driver: nvidia
               count: 1
               capabilities: [gpu]
    restart: unless-stopped
    # 简单的启动命令，避免复杂的集成
    command: ["sleep", "infinity"]  # 先保持容器运行，后续可以手动调试

networks:
  xconnector-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16  # 使用不同的子网避免冲突

volumes:
  etcd-data:
  xconnector-logs:
  dynamo-logs:
  model-cache: