version: '3.8'

services:
  dynamo-worker:
    image: dynamo-nvidia:v0.3.0-vllm0.8.4-lmcache0.2.1-inline
    container_name: dynamo-worker
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - ENABLE_XCONNECTOR=true
      - XCONNECTOR_SERVICE_URL=http://xconnector-service:8081
      - XCONNECTOR_FAIL_ON_ERROR=false
      - ETCD_ENDPOINTS=http://etcd:2379
      - ETCD_URL=http://etcd:2379
      - ETCD_HOST=etcd
      - ETCD_PORT=2379
      - NATS_URL=nats://nats:4222
      - NATS_SERVER=nats://nats:4222
      - NATS_HOST=nats
      - NATS_PORT=4222
      - ETCD_USERNAME=
      - ETCD_PASSWORD=
      - ETCD_AUTH_TOKEN=
      - PYTHONPATH=/workspace/examples/llm:/workspace/xconnector-integration:/workspace
      - PATH=/opt/dynamo/venv/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/bin
      - LOG_LEVEL=INFO
      - DYNAMO_CONFIG_TYPE=${DYNAMO_CONFIG_TYPE:-disagg.yaml}

    networks:
      - xconnector-net
    
    ports:
      - "8000:8000"
    
    volumes:
      - ../../integrations/dynamo/configs:/workspace/xconnector-configs:ro
      - ./docker-optimized-launcher.sh:/workspace/docker-optimized-launcher.sh:ro
      - ../../integrations/dynamo/startup-wrapper.py:/workspace/startup-wrapper.py:ro
      - ../../integrations/dynamo/extension_loader.py:/tmp/extension_loader.py:ro
      - ../../integrations/dynamo/registry.py:/tmp/registry.py:ro
      - ../../integrations/dynamo/__init__.py:/tmp/__init__.py:ro
      - xconnector-integration:/workspace/xconnector-integration
      - dynamo-logs:/workspace/logs
      - model-cache:/workspace/models
      - /data/model:/data/model:ro

    working_dir: /workspace/examples/llm

    command: ["bash", "/workspace/docker-optimized-launcher.sh"]

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 300s
    
    restart: on-failure:5
    
    depends_on:
      etcd:
        condition: service_healthy
      xconnector-service:
        condition: service_healthy
      nats:
        condition: service_started

  xconnector-service:
    image: xconnector-service:latest
    container_name: xconnector-service
    
    environment:
      - ETCD_HOST=etcd
      - ETCD_PORT=2379
      - NATS_URL=nats://nats:4222
      - XCONNECTOR_PORT=8081
      - LOG_LEVEL=INFO
      - PYTHONPATH=/app
    
    networks:
      - xconnector-net
    
    ports:
      - "8081:8081"
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    volumes:
      - xconnector-logs:/app/logs
      - ../../integrations/dynamo/configs/xconnector_config.yaml:/app/configs/xconnector_config.yaml:ro
    
    restart: unless-stopped
    
    depends_on:
      - etcd
      - nats

  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ENABLE_V2=false
      - ETCD_AUTH_TOKEN=
      - ETCD_ROOT_PASSWORD=
      - ETCD_USERNAME=
      - ETCD_PASSWORD=
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2380
      - ETCD_INITIAL_CLUSTER=etcd=http://etcd:2380
      - ETCD_NAME=etcd
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER_STATE=new
      - BITNAMI_DEBUG=true
      - ETCD_LOG_LEVEL=info
    
    networks:
      - xconnector-net
    
    ports:
      - "2379:2379"
      - "2380:2380"
    
    volumes:
      - etcd-data:/bitnami/etcd/data
    
    command: >
      sh -c "
        echo 'Starting etcd in no-auth mode...';
        export ALLOW_NONE_AUTHENTICATION=yes;
        export ETCD_AUTH_TOKEN='';
        export ETCD_ROOT_PASSWORD='';
        /opt/bitnami/scripts/etcd/entrypoint.sh /opt/bitnami/scripts/etcd/run.sh
      "
    
    healthcheck:
      test: ["CMD", "pgrep", "etcd"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s
    
    restart: unless-stopped

  nats:
    image: nats:latest
    container_name: nats
    
    networks:
      - xconnector-net
    
    ports:
      - "4222:4222"
      - "8222:8222"
    
    command: ["-js", "-m", "8222"]
    
    restart: unless-stopped

networks:
  xconnector-net:
    external: true
    name: xconnector-dynamo_xconnector-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  etcd-data:
    driver: local
  xconnector-logs:
    driver: local
  dynamo-logs:
    driver: local
  model-cache:
    driver: local
  xconnector-integration:
    driver: local